const templateRepository = require('../../infrastructure/repositories/TemplateRepository');

class TemplateUseCase {
    async createTemplate(templateData, userId) {
        if (!templateData.name || !templateData.html_content) {
            throw new Error('El nombre y el contenido HTML son requeridos para la plantilla');
        }

        // Add the creator user ID
        templateData.created_by = userId;

        // Save to DB (token is auto-generated by DB UUID default)
        const template = await templateRepository.create(templateData);
        return template;
    }

    async getAllTemplates() {
        return await templateRepository.findAll();
    }

    async getTemplateById(id) {
        const template = await templateRepository.findById(id);
        if (!template) {
            throw new Error('Plantilla no encontrada');
        }
        return template;
    }
}

module.exports = new TemplateUseCase();
